### ISSUE TITLE
Generate C file from multiple FIS files

### ISSUE THREAD

**Issue by karthiknadig** [karthiknadig/ArduinoFIS#1]
The generate currently works with a single FIS file. This should be changed to support multiple FIS files. The generated code should contain models for each of the FIS input. You should be able to call  the evaluation function for each of the models separately.

**Comment by snsvfi** [comment]
if you have free time please help me to generate c code from fis file,because makeproto can't be access and docdocker not support in my pc .thankyou so much.it mean a lot for me
[vp-sp rpm.zip](https://github.com/karthiknadig/ArduinoFIS/files/5598004/vp-sp.rpm.zip)

**Comment by karthiknadig** [comment]
Not enough demand for this.
