### ISSUE TITLE
error with nodeMcu v1.0

### ISSUE THREAD

**Issue by gunaone** [karthiknadig/ArduinoFIS#5]
i compiling with nodeMcu and getting error

**Comment by karthiknadig** [comment]
You might have to modify code for this manually. The generator was originally intended only for Arduino. The evaluation code itself should be fine, likely the issue is with how the pins are configured.

I will add support for this if I see enough demand for this.

**Comment by gunaone** [comment]
thanks. it will be nice if support in nodeMCU board
